name: Deployment PipeLine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
